[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "go.mongodb.org/mongo-driver"
  version = "1.3.1"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "4.0.3"

[[constraint]]
  name = "github.com/go-chi/render"
  version = "1.0.1"

[[constraint]]
  name = "github.com/go-chi/cors"
  version = "1.0.0"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"
